# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy Python requirements
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Expose port
EXPOSE 5000

# Start the app with Flask directly
CMD ["python", "radio_player_web.py"]
