INSERT INTO radios (name, url, genre) VALUES
('Mega Hits', 'https://playerservices.streamtheworld.com/api/livestream-redirect/MEGA_HITSAAC.aac', 'Pop'),
('Flash 80', 'https://manager7.streamradio.fr:1985/stream', '80s'),
('100% Radio 80', 'https://stream.100radio.net/radio-80', '80s'),
('RTL', 'https://stream.rtl.fr/rtl-1-44-128', 'Généraliste'),
('France Inter', 'https://icecast.radiofrance.fr/franceinter-midfi.mp3', 'Généraliste'),
('France Info', 'https://icecast.radiofrance.fr/franceinfo-midfi.mp3', 'Info'),
('France Culture', 'https://icecast.radiofrance.fr/franceculture-midfi.mp3', 'Culture'),
('Oui FM', 'https://stream.ouifm.fr/ouifm-1-44-128', 'Rock'),
('NRJ', 'https://stream.nrj.fr/nrj_151759.mp3', 'Pop'),
('Skyrock', 'https://icecast.skyrock.net/s/natio_128.mp3', 'Hip-Hop'),
('Fun Radio', 'https://stream.funradio.fr/fun_128.mp3', 'Dance'),
('Chérie FM', 'https://stream.cheriefm.fr/cheriefm_128.mp3', 'Pop'),
('Rire et Chansons', 'https://stream.rireetchansons.fr/rireetchansons-128.mp3', 'Humour'),
('Nostalgie', 'https://stream.nostalgie.fr/nostalgie-128.mp3', 'Oldies'),
('Europe 1', 'https://stream.europe1.fr/europe1-128.mp3', 'Info'),
('RFM', 'https://stream.rfm.fr/rfm_128.mp3', 'Pop'),
('Virgin Radio', 'https://stream.virginradio.fr/virgin-128.mp3', 'Rock'),
('Le Mouv''', 'https://icecast.radiofrance.fr/mouv-midfi.mp3', 'Pop-Rock'),
('FIP', 'https://icecast.radiofrance.fr/fip-midfi.mp3', 'Jazz'),
('Radio Nova', 'https://stream.nova.fm/nova-128.mp3', 'Electro');